# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# An example of Cloud Build configuration file for CI/CD pipeline.

steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "$PROJECT_ID"
      echo "$SERVICE_ACCOUNT_EMAIL"
      echo "***********************"

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['aa-integration-backend/deploy.sh']
  env:
  - 'GCP_PROJECT_ID=$PROJECT_ID'
  - 'ADMIN_ACCOUNT=$SERVICE_ACCOUNT_EMAIL'
  - 'AUTH_OPTION=Skip'
  - 'BACKEND_DIR=/aa-integration-backend'
  - 'CONNECTOR_SERVICE_NAME=ui-connector-presubmit-${BRANCH_NAME}'
  - 'INTERCEPTOR_SERVICE_NAME=cloud-pubsub-interceptor-presubmit-${BRANCH_NAME}'